const traduzioni = {
    it: {
        titolo_pagina: "DriverBook - NCC Noleggio Con Conducente",
        hero_title_1: "Il tuo autista privato",
        hero_title_2: "per ogni tua destinazione",
        hero_subtitle: "Prenota trasferimenti e disposizioni orarie per viaggi di piacere o di lavoro<br>Il tuo servizio NCC (Noleggio con Conducente) affidabile e discreto",
        btn_passengers: "Area Passeggeri",
        btn_drivers: "Area Autisti",
        footer_rights: "&copy; 2026 DriverBook. Tutti i diritti riservati.",
        ios_install_1: "Per installare l'app su iPhone o iPad:",
        ios_install_2: "1. Tocca l'icona <strong>Condividi</strong> in basso nel browser.",
        ios_install_3: "2. Seleziona <strong>Aggiungi alla schermata Home</strong>.",
        title_login_passeggeri: "Accesso Passeggeri",
        h1_login_passeggeri: "Accesso Passeggeri",
        msg_email_confermata: "Email confermata con successo. Effettua il login con le tue nuove credenziali.",
        label_email_accesso: "Email Accesso",
        label_password: "Password",
        btn_accedi: "Accedi",
        nota_impostazioni: "Tutte le impostazioni a tua disposizione sono accessibili dal menù account in alto a destra.",
        btn_chiudi_menu_testo: "CHIUDI MENU",
        menu_pub_login: "Accesso",
        menu_pub_reset: "Recupero Password",
        menu_pub_reg: "Registrazione",
        menu_pub_assist: "Assistenza",
        menu_home: "Pannello Utente",
        menu_prenota: "Prenota Servizio",
        menu_riepilogo: "Riepilogo Richiesta",
        menu_viaggi: "Viaggi in Programma",
        menu_storico: "Storico Viaggi",
        menu_profilo: "Modifica Profilo",
        menu_sicurezza: "Cambio Password",
        menu_assistenza: "Assistenza",
        title_reset_password: "Reset Password",
        h1_recupero_password: "Recupero Password",
        p_desc_recupero: "Inserisci l'indirizzo email associato al tuo account. Ti invieremo un link per creare una nuova password.",
        label_tua_email: "La tua Email",
        btn_invia_recupero_testo: "Invia Link di Recupero",
        title_reg_passeggero: "Registrazione Passeggero",
        h1_reg_passeggero: "Registrazione Passeggero",
        label_nome_cognome: "Nome e Cognome / Referente",
        label_telefono: "Telefono Cellulare",
        label_richiede_fattura: "Richiedo fatturazione elettronica (Azienda / Hotel)",
        label_ragione_sociale: "Ragione Sociale",
        label_piva_cf: "Partita IVA / Codice Fiscale",
        label_sdi: "Codice Destinatario SDI (7 caratteri)",
        nota_sdi: "Se non possiedi un codice SDI, inserisci 0000000 (sette zeri) e compila il campo PEC.",
        label_pec: "Indirizzo PEC",
        label_indirizzo_via: "Indirizzo Sede Legale (Via e Civico)",
        label_cap: "CAP",
        label_citta: "Città",
        label_provincia: "Provincia (Sigla)",
        label_come_notifiche: "Come vuoi ricevere le notifiche?",
        label_push: "Notifiche Push (Consigliata)",
        nota_push: "Istantanea su smartphone e PC.",
        label_notifica_email: "Email",
        errore_notifiche: "Seleziona un metodo.",
        errore_password: "La password deve avere almeno 8 caratteri, una maiuscola, una minuscola e un numero.",
        label_conferma_password: "Conferma Password",
        errore_coincidenza: "Le password non coincidono.",
        btn_registrati: "Registrati",
        title_assistenza: "Assistenza - DriverBook",
        h1_assistenza: "Assistenza",
        label_assistenza_email: "La tua email",
        label_descrivi_problema: "Descrivi il problema",
        btn_invia_richiesta: "Invia Richiesta",
        placeholder_assistenza: "Scrivi qui i dettagli della tua richiesta...",
        modale_uscita_titolo: "Attenzione",
        modale_uscita_testo: "Hai delle modifiche non salvate. Sei sicuro di voler abbandonare la pagina?",
        modale_uscita_btn_resta: "RESTA QUI",
        modale_uscita_btn_esci: "ESCI E PERDI",
        title_dash_passeggero: "DriverBook - Dashboard Passeggero",
        h1_ciao: "Ciao,",
        label_codice_cliente: "Codice Cliente:",
        btn_prenota_servizio_testo: "PRENOTA SERVIZIO",
        swipe_logout_testo: "SCORRI PER USCIRE DALL'ACCOUNT",
        title_prenota: "DriverBook - Prenota Servizio",
        h1_prenota: "Prenota Servizio",
        label_nome_pax: "Nome e Cognome Passeggero",
        nota_cartello: "(Per il cartello di benvenuto)",
        label_tel_pax: "Telefono Passeggero",
        nota_incontro: "(Per coordinare il punto d'incontro all'arrivo)",
        label_chk_ref: "La prenotazione viene effettuata da un referente? (es. Hotel, Azienda)",
        label_nome_ref: "Nome Referente",
        label_tel_ref: "Telefono Referente",
        nota_logistica: "(Per comunicazioni logistiche e amministrative)",
        label_tipo_servizio: "Tipo di Servizio",
        opt_seleziona: "Seleziona...",
        opt_tratta: "Servizio a Tratta Diretta",
        opt_disposizione: "Servizio a Disposizione Oraria",
        label_durata: "Durata Disposizione",
        opt_ore_min: "3 Ore (Minimo)",
        opt_ore_4: "4 Ore",
        opt_ore_5: "5 Ore",
        opt_ore_6: "6 Ore",
        opt_ore_7: "7 Ore",
        opt_ore_8: "8 Ore",
        opt_ore_9: "9 Ore",
        opt_ore_10: "10 Ore",
        opt_ore_11: "11 Ore",
        opt_ore_max: "12 Ore (Massimo)",
        label_partenza: "Luogo di Partenza",
        label_arrivo: "Luogo di Destinazione",
        label_itinerario: "Itinerario Previsto (Opzionale)",
        nota_itinerario: "(Inserisci qui una traccia indicativa delle tappe o delle località previste, per permettere al conducente di pianificare al meglio il servizio)",
        label_chk_hub: "Il servizio prevede la partenza o l'arrivo in Aeroporto, Stazione o Porto?",
        label_info_trasporto: "Numero del Volo, Treno o Nave",
        nota_trasporto: "(Necessario all'autista per identificare il terminal, il punto di ingresso/uscita e monitorare lo stato in tempo reale)",
        label_data_servizio: "Data del Servizio",
        label_ora_partenza: "Ora di Partenza",
        err_preavviso: "Preavviso minimo richiesto: 3 ore",
        label_num_pax: "Numero Passeggeri",
        opt_pax_1: "1 Passeggero",
        opt_pax_2: "2 Passeggeri",
        opt_pax_3: "3 Passeggeri",
        opt_pax_4: "4 Passeggeri",
        opt_pax_5: "5 Passeggeri",
        opt_pax_6: "6 Passeggeri",
        opt_pax_7: "7 Passeggeri",
        label_valigie: "Valigie Grandi (Da Stiva)",
        opt_val_0: "0 Valigie Grandi",
        opt_val_1: "1 Valigia Grande",
        opt_val_2: "2 Valigie Grandi",
        opt_val_3: "3 Valigie Grandi",
        opt_val_4: "4 Valigie Grandi",
        opt_val_5: "5 Valigie Grandi",
        opt_val_6: "6 Valigie Grandi",
        opt_val_7: "7 Valigie Grandi",
        label_trolley: "Trolley (Bagaglio a Mano)",
        opt_tro_0: "0 Trolley",
        opt_tro_1: "1 Trolley",
        opt_tro_2: "2 Trolley",
        opt_tro_3: "3 Trolley",
        opt_tro_4: "4 Trolley",
        opt_tro_5: "5 Trolley",
        opt_tro_6: "6 Trolley",
        opt_tro_7: "7 Trolley",
        label_seleziona_vettura: "Seleziona la Vettura Desiderata",
        vettura_berlina_comfort: "Berlina Comfort",
        vettura_berlina_lusso: "Berlina Lusso",
        vettura_van_comfort: "Van Comfort",
        vettura_disponibile: "Disponibile",
        alert_bagagli_eccedenza: "Per motivi di sicurezza e in conformità con le normative vigenti, tutti i bagagli devono essere alloggiati esclusivamente nel vano di carico. La quantità selezionata supera la capacità massima dei vani di carico delle nostre vetture.<br><br>Per procedere, vi invitiamo ad effettuare due prenotazioni separate, distribuendo passeggeri e bagagli su due vetture distinte.",
        label_note_servizio: "Note e Richieste Particolari",
        nota_note: "(Segnala qui la necessità di seggiolini, contatti di assistenti o altre necessità logistiche)",
        err_selezione_vettura: "Per procedere è necessario selezionare una delle vetture disponibili.",
        btn_procedi: "Procedi",
        js_login_loading: "Accesso in corso...",
        js_login_err_active: "Account non attivo. Hai confermato il link via email?",
        js_login_err_invalid: "Email o password non validi.",
        js_login_err_pax: "Account non registrato come Passeggero.",
        js_login_err_driver: "Account non autorizzato come Autista.",
        js_login_success: "Accesso effettuato!",
        js_reg_err_exists: "Questa email risulta già registrata. Inserisci un indirizzo diverso oppure vai alla pagina di Login.",
        js_reg_err_generic: "Non è stato possibile completare la registrazione: ",
        js_reg_success: "Registrato! Conferma la mail per attivarlo.",
        js_prof_err_vat: "Conferma disattivazione P.IVA prima di salvare!",
        js_prof_loading: "Salvataggio in corso...",
        js_prof_email_success: "Email aggiornata! Ti scolleghiamo, conferma il link ricevuto.",
        js_prof_success: "Modifiche salvate con successo!",
        js_prof_err_email_exists: "La mail scelta è già registrata.",
        js_prof_err_save: "Errore durante il salvataggio. Riprova.",
        js_rec_loading: "Invio richiesta...",
        js_rec_success: "Email di ripristino inviata!",
        js_rec_err: "Errore di invio",
        js_rec_proc: "Elaborazione in corso...",
        js_rec_email_sent: "Se registrato, riceverai un'email a breve!",
        js_rec_conn_err: "Errore di connessione. Riprova.",
        js_pass_loading: "Salvataggio in corso...",
        js_pass_err_same: "La nuova password digitata è uguale all'attuale, non hai bisogno di reimpostarla.",
        js_pass_err_update: "Impossibile aggiornare la password. Link scaduto o errore server.",
        js_pass_success: "Password aggiornata! Accesso in corso...",
        js_assist_loading: "Invio in corso...",
        js_assist_success: "Richiesta inviata correttamente!",
        js_assist_err: "Errore durante l'invio. Riprova più tardi.",
        js_check_success_title: "Richiesta Inviata!",
        js_check_success_text: "La tua prenotazione è stata registrata con successo.<br><br>Codice: ",
        js_check_btn_dash: "VAI AL PANNELLO UTENTE",
        js_check_err_title: "Errore",
        js_check_err_text: "Si è verificato un errore durante l'invio della richiesta nel database. Riprova tra poco.",
        js_check_btn_close: "Chiudi",
        js_check_redirect: "Nessun dato di prenotazione trovato.<br><br>Reindirizzamento in corso...",
        js_link_exp_title: "Link Scaduto o<br>Non Valido",
        js_link_exp_text: "Il link di sicurezza che hai utilizzato non è più valido.<br>Ti preghiamo di effettuare una nuova richiesta.",
        js_link_exp_btn: "Richiedi un nuovo link",
        js_vettura_disp: "Disponibile",
        js_vettura_sel: "Selezionata",
        js_vettura_non_disp: "Non disponibile",
        js_motivo_comfort: "Per garantire il massimo comfort e l'esclusività del servizio sulle nostre berline, ospitiamo un massimo di due passeggeri nella parte posteriore. Oltre questa capienza è prevista la selezione del Van.",
        js_motivo_bagagli: "Per motivi di sicurezza e in conformità con le normative vigenti, tutti i bagagli devono essere alloggiati esclusivamente nel vano di carico. La quantità selezionata supera la capacità massima del bagagliaio.",
        title_checkout: "DriverBook - Riepilogo Prenotazione",
        h1_checkout: "Riepilogo Richiesta",
        h2_passeggero: "Passeggero",
        lbl_nome_cognome_pax: "Nome e Cognome",
        lbl_tel_pax: "Telefono Passeggero",
        h2_referente: "Referente Prenotazione",
        lbl_nome_ref: "Nome Azienda / Referente",
        lbl_tel_ref: "Telefono Referente",
        h2_dettagli_servizio: "Dettagli Servizio",
        lbl_tipologia: "Tipologia Servizio",
        lbl_durata: "Durata Disposizione",
        lbl_vettura_richiesta: "Vettura Richiesta",
        lbl_data_ora: "Data e Ora Partenza",
        h2_itinerario: "Itinerario",
        lbl_partenza: "Luogo di Partenza",
        lbl_arrivo: "Luogo di Destinazione",
        lbl_itinerario_previsto: "Itinerario Previsto",
        h2_monitoraggio: "Monitoraggio",
        lbl_volo_treno_nave: "Volo / Treno / Nave",
        h2_logistica: "Logistica e Note",
        lbl_pax_bagagli: "Passeggeri e Bagagli",
        lbl_note_richieste: "Note e Richieste Particolari",
        h1_totale: "Totale",
        btn_invia_richiesta_checkout: "Invia Richiesta",
        title_viaggi_programma: "Viaggi in Programma - DriverBook",
        h1_viaggi_programma: "Viaggi in programma",
        lbl_nessun_viaggio_gestire: "Nessun viaggio in programma da gestire.",
        h2_mio_account: "Il Mio Account",
        title_storico_viaggi: "Storico Viaggi - DriverBook",
        h1_storico_viaggi: "Storico Viaggi",
        lbl_nessuno_storico: "Nessuno storico disponibile.",
        title_modifica_profilo: "Modifica Profilo - DriverBook",
        h1_modifica_profilo: "Modifica Profilo",
        nota_modifica_email: "La modifica dell'email richiederà la conferma tramite un link inviato al nuovo indirizzo.",
        alert_chiusura_fatturazione: "Attenzione: disattivando questa opzione, cancellerai irreversibilmente tutti i tuoi dati di fatturazione. Vuoi procedere?",
        btn_annulla_chiusura: "ANNULLA",
        btn_conferma_chiusura: "CONFERMA E CANCELLA",
        err_seleziona_notifica: "Seleziona almeno un metodo per ricevere le notifiche.",
        btn_salva_profilo: "Salva Modifiche Profilo",
        title_cambio_password: "Cambio Password - DriverBook",
        h1_cambio_password: "Cambio Password",
        btn_reset_password_testo: "RESET PASSWORD",
        title_reimposta_password: "Reimposta Password - DriverBook",
        h1_reimposta_password: "Reimposta Password",
        label_nuova_password: "Nuova Password",
        label_conferma_nuova_password: "Conferma Nuova Password",
        btn_salva_nuova_password: "Salva Nuova Password",
        ph_nome_reg: "Mario Rossi",
        ph_nome_pax: "Andrea Bianchi",
        ph_nome_ref: "Studio Bianchi / Hotel Vista",
        ph_indirizzo: "Cerca indirizzo, hotel, aeroporto...",
        ph_itinerario: "Milano Centro -> Monza -> Ritorno a Milano",
        ph_trasporto: "AZ204 / Frecciarossa 9512",
        ph_note: "Richiesto seggiolino bimbo 15-36 kg...",
        ph_ragione_sociale: "Hotel Roma SRL",
        ph_sdi: "M5UXCR1 oppure 0000000",
        ph_via: "Via Roma 10",
        ph_citta: "Milano"
    },
    en: {
        titolo_pagina: "DriverBook - Chauffeur Service",
        hero_title_1: "Your private driver",
        hero_title_2: "for every destination",
        hero_subtitle: "Book transfers and hourly dispositions for leisure or business trips<br>Your reliable and discreet chauffeur service",
        btn_passengers: "Passenger Area",
        btn_drivers: "Driver Area",
        footer_rights: "&copy; 2026 DriverBook. All rights reserved.",
        ios_install_1: "To install the app on iPhone or iPad:",
        ios_install_2: "1. Tap the <strong>Share</strong> icon at the bottom of the browser.",
        ios_install_3: "2. Select <strong>Add to Home Screen</strong>.",
        title_login_passeggeri: "Passenger Login",
        h1_login_passeggeri: "Passenger Login",
        msg_email_confermata: "Email successfully confirmed. Please log in with your new credentials.",
        label_email_accesso: "Login Email",
        label_password: "Password",
        btn_accedi: "Log In",
        nota_impostazioni: "All your available settings can be accessed from the account menu in the top right corner.",
        btn_chiudi_menu_testo: "CLOSE MENU",
        menu_pub_login: "Log In",
        menu_pub_reset: "Password Recovery",
        menu_pub_reg: "Sign Up",
        menu_pub_assist: "Support",
        menu_home: "User Dashboard",
        menu_prenota: "Book Service",
        menu_riepilogo: "Request Summary",
        menu_viaggi: "Upcoming Trips",
        menu_storico: "Trip History",
        menu_profilo: "Edit Profile",
        menu_sicurezza: "Change Password",
        menu_assistenza: "Support",
        title_reset_password: "Reset Password",
        h1_recupero_password: "Password Recovery",
        p_desc_recupero: "Enter the email address associated with your account. We will send you a link to create a new password.",
        label_tua_email: "Your Email",
        btn_invia_recupero_testo: "Send Recovery Link",
        title_reg_passeggero: "Passenger Registration",
        h1_reg_passeggero: "Passenger Registration",
        label_nome_cognome: "Full Name / Contact Person",
        label_telefono: "Mobile Phone",
        label_richiede_fattura: "I require electronic invoicing (Italian Registered Companies Only)",
        label_ragione_sociale: "Company Name",
        label_piva_cf: "VAT Number / Tax Code",
        label_sdi: "SDI Recipient Code (7 characters)",
        nota_sdi: "If you do not have an SDI code, enter 0000000 (seven zeros) and fill in the PEC field.",
        label_pec: "PEC Email Address",
        label_indirizzo_via: "Registered Office Address (Street and Number)",
        label_cap: "ZIP Code",
        label_citta: "City",
        label_provincia: "Province (Code)",
        label_come_notifiche: "How would you like to receive notifications?",
        label_push: "Push Notifications (Recommended)",
        nota_push: "Instant on smartphone and PC.",
        label_notifica_email: "Email",
        errore_notifiche: "Please select a method.",
        errore_password: "Minimum 8 characters, one uppercase, one lowercase and one number.",
        label_conferma_password: "Confirm Password",
        errore_coincidenza: "Passwords do not match.",
        btn_registrati: "Sign Up",
        title_assistenza: "Support - DriverBook",
        h1_assistenza: "Support",
        label_assistenza_email: "Your email",
        label_descrivi_problema: "Describe the problem",
        btn_invia_richiesta: "Send Request",
        placeholder_assistenza: "Write the details of your request here...",
        modale_uscita_titolo: "Warning",
        modale_uscita_testo: "You have unsaved changes. Are you sure you want to leave this page?",
        modale_uscita_btn_resta: "STAY",
        modale_uscita_btn_esci: "LEAVE",
        title_dash_passeggero: "DriverBook - Passenger Dashboard",
        h1_ciao: "Hello,",
        label_codice_cliente: "Customer Code:",
        btn_prenota_servizio_testo: "BOOK SERVICE",
        swipe_logout_testo: "SWIPE TO LOG OUT",
        title_prenota: "DriverBook - Book Service",
        h1_prenota: "Book Service",
        label_nome_pax: "Passenger Full Name",
        nota_cartello: "(For the welcome sign)",
        label_tel_pax: "Passenger Phone",
        nota_incontro: "(To coordinate the meeting point upon arrival)",
        label_chk_ref: "Is the booking made by a reference person? (e.g., Hotel, Company)",
        label_nome_ref: "Reference Name",
        label_tel_ref: "Reference Phone",
        nota_logistica: "(For logistical and administrative communications)",
        label_tipo_servizio: "Service Type",
        opt_seleziona: "Select...",
        opt_tratta: "Direct Transfer Service",
        opt_disposizione: "Hourly Disposition Service",
        label_durata: "Disposition Duration",
        opt_ore_min: "3 Hours (Minimum)",
        opt_ore_4: "4 Hours",
        opt_ore_5: "5 Hours",
        opt_ore_6: "6 Hours",
        opt_ore_7: "7 Hours",
        opt_ore_8: "8 Hours",
        opt_ore_9: "9 Hours",
        opt_ore_10: "10 Hours",
        opt_ore_11: "11 Hours",
        opt_ore_max: "12 Hours (Maximum)",
        label_partenza: "Pickup Location",
        label_arrivo: "Drop-off Location",
        label_itinerario: "Planned Itinerary (Optional)",
        nota_itinerario: "(Enter a rough outline of the stops or locations here, to allow the driver to best plan the service)",
        label_chk_hub: "Does the service involve a departure or arrival at an Airport, Station, or Port?",
        label_info_trasporto: "Flight, Train, or Ship Number",
        nota_trasporto: "(Required for the driver to identify the terminal, entry/exit point, and monitor status in real-time)",
        label_data_servizio: "Service Date",
        label_ora_partenza: "Pickup Time",
        err_preavviso: "Minimum advance notice required: 3 hours",
        label_num_pax: "Number of Passengers",
        opt_pax_1: "1 Passenger",
        opt_pax_2: "2 Passengers",
        opt_pax_3: "3 Passengers",
        opt_pax_4: "4 Passengers",
        opt_pax_5: "5 Passengers",
        opt_pax_6: "6 Passengers",
        opt_pax_7: "7 Passengers",
        label_valigie: "Large Suitcases (Checked Baggage)",
        opt_val_0: "0 Large Suitcases",
        opt_val_1: "1 Large Suitcase",
        opt_val_2: "2 Large Suitcases",
        opt_val_3: "3 Large Suitcases",
        opt_val_4: "4 Large Suitcases",
        opt_val_5: "5 Large Suitcases",
        opt_val_6: "6 Large Suitcases",
        opt_val_7: "7 Large Suitcases",
        label_trolley: "Carry-on Baggage (Trolley)",
        opt_tro_0: "0 Carry-ons",
        opt_tro_1: "1 Carry-on",
        opt_tro_2: "2 Carry-ons",
        opt_tro_3: "3 Carry-ons",
        opt_tro_4: "4 Carry-ons",
        opt_tro_5: "5 Carry-ons",
        opt_tro_6: "6 Carry-ons",
        opt_tro_7: "7 Carry-ons",
        label_seleziona_vettura: "Select Desired Vehicle",
        vettura_berlina_comfort: "Comfort Sedan",
        vettura_berlina_lusso: "Luxury Sedan",
        vettura_van_comfort: "Comfort Van",
        vettura_disponibile: "Available",
        alert_bagagli_eccedenza: "For safety reasons and in compliance with current regulations, all luggage must be stored exclusively in the luggage compartment. The selected quantity exceeds the maximum capacity of our vehicles' cargo areas.<br><br>To proceed, please make two separate bookings, distributing passengers and luggage across two distinct vehicles.",
        label_note_servizio: "Notes and Special Requests",
        nota_note: "(Indicate the need for child seats, assistant contacts, or other logistical requirements here)",
        err_selezione_vettura: "To proceed, you must select one of the available vehicles.",
        btn_procedi: "Proceed",
        js_login_loading: "Logging in...",
        js_login_err_active: "Account not active. Have you confirmed the email link?",
        js_login_err_invalid: "Invalid email or password.",
        js_login_err_pax: "Account not registered as Passenger.",
        js_login_err_driver: "Account not authorized as Driver.",
        js_login_success: "Login successful!",
        js_reg_err_exists: "This email is already registered. Enter a different address or go to the Login page.",
        js_reg_err_generic: "Registration could not be completed: ",
        js_reg_success: "Registered! Confirm the email to activate it.",
        js_prof_err_vat: "Confirm VAT deactivation before saving!",
        js_prof_loading: "Saving...",
        js_prof_email_success: "Email updated! Logging you out, confirm the received link.",
        js_prof_success: "Changes saved successfully!",
        js_prof_err_email_exists: "The chosen email is already registered.",
        js_prof_err_save: "Error saving. Please try again.",
        js_rec_loading: "Sending request...",
        js_rec_success: "Recovery email sent!",
        js_rec_err: "Send error",
        js_rec_proc: "Processing...",
        js_rec_email_sent: "If registered, you will receive an email shortly!",
        js_rec_conn_err: "Connection error. Please try again.",
        js_pass_loading: "Saving...",
        js_pass_err_same: "The new password entered is the same as the current one, you do not need to reset it.",
        js_pass_err_update: "Unable to update password. Link expired or server error.",
        js_pass_success: "Password updated! Logging in...",
        js_assist_loading: "Sending...",
        js_assist_success: "Request sent successfully!",
        js_assist_err: "Error sending. Please try again later.",
        js_check_success_title: "Request Sent!",
        js_check_success_text: "Your booking has been successfully registered.<br><br>Code: ",
        js_check_btn_dash: "GO TO DASHBOARD",
        js_check_err_title: "Error",
        js_check_err_text: "An error occurred while sending the request to the database. Please try again shortly.",
        js_check_btn_close: "Close",
        js_check_redirect: "No booking data found.<br><br>Redirecting...",
        js_link_exp_title: "Expired or<br>Invalid Link",
        js_link_exp_text: "The security link you used is no longer valid.<br>Please make a new request.",
        js_link_exp_btn: "Request a new link",
        js_vettura_disp: "Available",
        js_vettura_sel: "Selected",
        js_vettura_non_disp: "Not available",
        js_motivo_comfort: "To ensure maximum comfort and exclusivity of the service on our sedans, we accommodate a maximum of two passengers in the rear. Beyond this capacity, the selection of the Van is required.",
        js_motivo_bagagli: "For safety reasons and in compliance with current regulations, all luggage must be stored exclusively in the luggage compartment. The selected quantity exceeds the maximum trunk capacity.",
        title_checkout: "DriverBook - Booking Summary",
        h1_checkout: "Request Summary",
        h2_passeggero: "Passenger",
        lbl_nome_cognome_pax: "Full Name",
        lbl_tel_pax: "Passenger Phone",
        h2_referente: "Booking Reference",
        lbl_nome_ref: "Company Name / Reference",
        lbl_tel_ref: "Reference Phone",
        h2_dettagli_servizio: "Service Details",
        lbl_tipologia: "Service Type",
        lbl_durata: "Disposition Duration",
        lbl_vettura_richiesta: "Requested Vehicle",
        lbl_data_ora: "Departure Date and Time",
        h2_itinerario: "Itinerary",
        lbl_partenza: "Pickup Location",
        lbl_arrivo: "Drop-off Location",
        lbl_itinerario_previsto: "Planned Itinerary",
        h2_monitoraggio: "Monitoring",
        lbl_volo_treno_nave: "Flight / Train / Ship",
        h2_logistica: "Logistics and Notes",
        lbl_pax_bagagli: "Passengers and Luggage",
        lbl_note_richieste: "Notes and Special Requests",
        h1_totale: "Total",
        btn_invia_richiesta_checkout: "Send Request",
        title_viaggi_programma: "Upcoming Trips - DriverBook",
        h1_viaggi_programma: "Upcoming Trips",
        lbl_nessun_viaggio_gestire: "No upcoming trips to manage.",
        h2_mio_account: "My Account",
        title_storico_viaggi: "Trip History - DriverBook",
        h1_storico_viaggi: "Trip History",
        lbl_nessuno_storico: "No history available.",
        title_modifica_profilo: "Edit Profile - DriverBook",
        h1_modifica_profilo: "Edit Profile",
        nota_modifica_email: "Changing your email will require confirmation via a link sent to the new address.",
        alert_chiusura_fatturazione: "Warning: by disabling this option, you will irreversibly delete all your billing data. Do you want to proceed?",
        btn_annulla_chiusura: "CANCEL",
        btn_conferma_chiusura: "CONFIRM AND DELETE",
        err_seleziona_notifica: "Please select at least one notification method.",
        btn_salva_profilo: "Save Profile Changes",
        title_cambio_password: "Change Password - DriverBook",
        h1_cambio_password: "Change Password",
        btn_reset_password_testo: "RESET PASSWORD",
        title_reimposta_password: "Reset Password - DriverBook",
        h1_reimposta_password: "Set New Password",
        label_nuova_password: "New Password",
        label_conferma_nuova_password: "Confirm New Password",
        btn_salva_nuova_password: "Save New Password",
        ph_nome_reg: "John Smith",
        ph_nome_pax: "John Smith",
        ph_nome_ref: "Smith Firm / Hotel Vista",
        ph_indirizzo: "Search address, hotel, airport...",
        ph_itinerario: "Milan Center -> Monza -> Return to Milan",
        ph_trasporto: "Flight AZ204 / Train 9512",
        ph_note: "Child seat required 15-36 kg...",
        ph_ragione_sociale: "Hotel Rome LTD",
        ph_sdi: "M5UXCR1 or 0000000",
        ph_via: "10 Rome Street",
        ph_citta: "Milan"
    }
};