const traduzioni = {
    it: {
        // --- BASE & HTML ---
        titolo_pagina: "DriverBook - NCC Noleggio Con Conducente",
        hero_title_1: "Il tuo autista privato",
        hero_title_2: "per ogni tua destinazione",
        hero_subtitle: "Prenota trasferimenti e disposizioni orarie per viaggi di piacere o di lavoro<br>Il tuo servizio NCC (Noleggio con Conducente) affidabile e discreto",
        btn_passengers: "Area Passeggeri",
        btn_drivers: "Area Autisti",
        footer_rights: "&copy; 2026 DriverBook. Tutti i diritti riservati.",
        ios_install_1: "Per installare l'app su iPhone o iPad:",
        ios_install_2: "1. Tocca l'icona <strong>Condividi</strong> in basso nel browser.",
        ios_install_3: "2. Seleziona <strong>Aggiungi alla schermata Home</strong>.",
        title_login_passeggeri: "Accesso Passeggeri",
        h1_login_passeggeri: "Accesso Passeggeri",
        msg_email_confermata: "Email confermata con successo. Effettua il login con le tue nuove credenziali.",
        label_email_accesso: "Email Accesso",
        label_password: "Password",
        btn_accedi: "Accedi",
        nota_impostazioni: "Tutte le impostazioni a tua disposizione sono accessibili dal menù account in alto a destra.",
        btn_chiudi_menu_testo: "CHIUDI MENU",
        menu_pub_login: "Accesso",
        menu_pub_reset: "Recupero Password",
        menu_pub_reg: "Registrazione",
        menu_pub_assist: "Assistenza",
        menu_home: "Pannello Utente",
        menu_prenota: "Prenota Servizio",
        menu_riepilogo: "Riepilogo Richiesta",
        menu_viaggi: "Viaggi in Programma",
        menu_storico: "Storico Viaggi",
        menu_profilo: "Modifica Profilo",
        menu_sicurezza: "Cambio Password",
        menu_assistenza: "Assistenza",
        title_reset_password: "Reset Password",
        h1_recupero_password: "Recupero Password",
        p_desc_recupero: "Inserisci l'indirizzo email associato al tuo account. Ti invieremo un link per creare una nuova password.",
        label_tua_email: "La tua Email",
        btn_invia_recupero_testo: "Invia Link di Recupero",
        title_reg_passeggero: "Registrazione Passeggero",
        h1_reg_passeggero: "Registrazione Passeggero",
        label_nome_cognome: "Nome e Cognome / Referente",
        label_telefono: "Telefono Cellulare",
        label_richiede_fattura: "Richiedo fatturazione elettronica (Azienda / Hotel)",
        label_ragione_sociale: "Ragione Sociale",
        label_piva_cf: "Partita IVA / Codice Fiscale",
        label_sdi: "Codice Destinatario SDI (7 caratteri)",
        nota_sdi: "Se non possiedi un codice SDI, inserisci 0000000 (sette zeri) e compila il campo PEC.",
        label_pec: "Indirizzo PEC",
        label_indirizzo_via: "Indirizzo Sede Legale (Via e Civico)",
        label_cap: "CAP",
        label_citta: "Città",
        label_provincia: "Provincia (Sigla)",
        label_come_notifiche: "Come vuoi ricevere le notifiche?",
        label_push: "Notifiche Push (Consigliata)",
        nota_push: "Istantanea su smartphone e PC.",
        label_notifica_email: "Email",
        errore_notifiche: "Seleziona un metodo.",
        errore_password: "Minimo 8 caratteri, una maiuscola, una minuscola e un numero.",
        label_conferma_password: "Conferma Password",
        errore_coincidenza: "Le password non coincidono.",
        btn_registrati: "Registrati",
        title_assistenza: "Assistenza - DriverBook",
        h1_assistenza: "Assistenza",
        label_assistenza_email: "La tua email",
        label_descrivi_problema: "Descrivi il problema",
        btn_invia_richiesta: "Invia Richiesta",
        placeholder_assistenza: "Scrivi qui i dettagli della tua richiesta...",
        modale_uscita_titolo: "Attenzione",
        modale_uscita_testo: "Hai delle modifiche non salvate. Sei sicuro di voler abbandonare la pagina?",
        modale_uscita_btn_resta: "RESTA QUI",
        modale_uscita_btn_esci: "ESCI E PERDI",

        // --- DINAMICHE JAVASCRIPT ---
        js_login_loading: "Accesso in corso...",
        js_login_err_active: "Account non attivo. Hai confermato il link via email?",
        js_login_err_invalid: "Email o password non validi.",
        js_login_err_pax: "Account non registrato come Passeggero.",
        js_login_err_driver: "Account non autorizzato come Autista.",
        js_login_success: "Accesso effettuato!",
        
        js_reg_err_exists: "Questa email risulta già registrata. Inserisci un indirizzo diverso oppure vai alla pagina di Login.",
        js_reg_err_generic: "Non è stato possibile completare la registrazione: ",
        js_reg_success: "Registrato! Conferma la mail per attivarlo.",
        
        js_prof_err_vat: "Conferma disattivazione P.IVA prima di salvare!",
        js_prof_loading: "Salvataggio in corso...",
        js_prof_email_success: "Email aggiornata! Ti scolleghiamo, conferma il link ricevuto.",
        js_prof_success: "Modifiche salvate con successo!",
        js_prof_err_email_exists: "La mail scelta è già registrata.",
        js_prof_err_save: "Errore durante il salvataggio. Riprova.",
        
        js_rec_loading: "Invio richiesta...",
        js_rec_success: "Email di ripristino inviata!",
        js_rec_err: "Errore di invio",
        js_rec_proc: "Elaborazione in corso...",
        js_rec_email_sent: "Se registrato, riceverai un'email a breve!",
        js_rec_conn_err: "Errore di connessione. Riprova.",
        
        js_pass_loading: "Salvataggio in corso...",
        js_pass_err_same: "La nuova password digitata è uguale all'attuale, non hai bisogno di reimpostarla.",
        js_pass_err_update: "Impossibile aggiornare la password. Link scaduto o errore server.",
        js_pass_success: "Password aggiornata! Accesso in corso...",
        
        js_assist_loading: "Invio in corso...",
        js_assist_success: "Richiesta inviata correttamente!",
        js_assist_err: "Errore durante l'invio. Riprova più tardi.",
        
        js_check_success_title: "Richiesta Inviata!",
        js_check_success_text: "La tua prenotazione è stata registrata con successo.<br><br>Codice: ",
        js_check_btn_dash: "VAI AL PANNELLO UTENTE",
        js_check_err_title: "Errore",
        js_check_err_text: "Si è verificato un errore durante l'invio della richiesta nel database. Riprova tra poco.",
        js_check_btn_close: "Chiudi",
        js_check_redirect: "Nessun dato di prenotazione trovato.<br><br>Reindirizzamento in corso...",
        
        js_link_exp_title: "Link Scaduto o<br>Non Valido",
        js_link_exp_text: "Il link di sicurezza che hai utilizzato non è più valido.<br>Ti preghiamo di effettuare una nuova richiesta.",
        js_link_exp_btn: "Richiedi un nuovo link"
    },
    en: {
        // --- BASE & HTML ---
        titolo_pagina: "DriverBook - Chauffeur Service",
        hero_title_1: "Your private driver",
        hero_title_2: "for every destination",
        hero_subtitle: "Book transfers and hourly dispositions for leisure or business trips<br>Your reliable and discreet chauffeur service",
        btn_passengers: "Passenger Area",
        btn_drivers: "Driver Area",
        footer_rights: "&copy; 2026 DriverBook. All rights reserved.",
        ios_install_1: "To install the app on iPhone or iPad:",
        ios_install_2: "1. Tap the <strong>Share</strong> icon at the bottom of the browser.",
        ios_install_3: "2. Select <strong>Add to Home Screen</strong>.",
        title_login_passeggeri: "Passenger Login",
        h1_login_passeggeri: "Passenger Login",
        msg_email_confermata: "Email successfully confirmed. Please log in with your new credentials.",
        label_email_accesso: "Login Email",
        label_password: "Password",
        btn_accedi: "Log In",
        nota_impostazioni: "All your available settings can be accessed from the account menu in the top right corner.",
        btn_chiudi_menu_testo: "CLOSE MENU",
        menu_pub_login: "Log In",
        menu_pub_reset: "Password Recovery",
        menu_pub_reg: "Sign Up",
        menu_pub_assist: "Support",
        menu_home: "User Dashboard",
        menu_prenota: "Book Service",
        menu_riepilogo: "Request Summary",
        menu_viaggi: "Upcoming Trips",
        menu_storico: "Trip History",
        menu_profilo: "Edit Profile",
        menu_sicurezza: "Change Password",
        menu_assistenza: "Support",
        title_reset_password: "Reset Password",
        h1_recupero_password: "Password Recovery",
        p_desc_recupero: "Enter the email address associated with your account. We will send you a link to create a new password.",
        label_tua_email: "Your Email",
        btn_invia_recupero_testo: "Send Recovery Link",
        title_reg_passeggero: "Passenger Registration",
        h1_reg_passeggero: "Passenger Registration",
        label_nome_cognome: "Full Name / Contact Person",
        label_telefono: "Mobile Phone",
        label_richiede_fattura: "I require electronic invoicing (Italian Registered Companies Only)",
        label_ragione_sociale: "Company Name",
        label_piva_cf: "VAT Number / Tax Code",
        label_sdi: "SDI Recipient Code (7 characters)",
        nota_sdi: "If you do not have an SDI code, enter 0000000 (seven zeros) and fill in the PEC field.",
        label_pec: "PEC Email Address",
        label_indirizzo_via: "Registered Office Address (Street and Number)",
        label_cap: "ZIP Code",
        label_citta: "City",
        label_provincia: "Province (Code)",
        label_come_notifiche: "How would you like to receive notifications?",
        label_push: "Push Notifications (Recommended)",
        nota_push: "Instant on smartphone and PC.",
        label_notifica_email: "Email",
        errore_notifiche: "Please select a method.",
        errore_password: "Minimum 8 characters, one uppercase, one lowercase and one number.",
        label_conferma_password: "Confirm Password",
        errore_coincidenza: "Passwords do not match.",
        btn_registrati: "Sign Up",
        title_assistenza: "Support - DriverBook",
        h1_assistenza: "Support",
        label_assistenza_email: "Your email",
        label_descrivi_problema: "Describe the problem",
        btn_invia_richiesta: "Send Request",
        placeholder_assistenza: "Write the details of your request here...",
        modale_uscita_titolo: "Warning",
        modale_uscita_testo: "You have unsaved changes. Are you sure you want to leave this page?",
        modale_uscita_btn_resta: "STAY",
        modale_uscita_btn_esci: "LEAVE",

        // --- DINAMICHE JAVASCRIPT ---
        js_login_loading: "Logging in...",
        js_login_err_active: "Account not active. Have you confirmed the email link?",
        js_login_err_invalid: "Invalid email or password.",
        js_login_err_pax: "Account not registered as Passenger.",
        js_login_err_driver: "Account not authorized as Driver.",
        js_login_success: "Login successful!",
        
        js_reg_err_exists: "This email is already registered. Enter a different address or go to the Login page.",
        js_reg_err_generic: "Registration could not be completed: ",
        js_reg_success: "Registered! Confirm the email to activate it.",
        
        js_prof_err_vat: "Confirm VAT deactivation before saving!",
        js_prof_loading: "Saving...",
        js_prof_email_success: "Email updated! Logging you out, confirm the received link.",
        js_prof_success: "Changes saved successfully!",
        js_prof_err_email_exists: "The chosen email is already registered.",
        js_prof_err_save: "Error saving. Please try again.",
        
        js_rec_loading: "Sending request...",
        js_rec_success: "Recovery email sent!",
        js_rec_err: "Send error",
        js_rec_proc: "Processing...",
        js_rec_email_sent: "If registered, you will receive an email shortly!",
        js_rec_conn_err: "Connection error. Please try again.",
        
        js_pass_loading: "Saving...",
        js_pass_err_same: "The new password entered is the same as the current one, you do not need to reset it.",
        js_pass_err_update: "Unable to update password. Link expired or server error.",
        js_pass_success: "Password updated! Logging in...",
        
        js_assist_loading: "Sending...",
        js_assist_success: "Request sent successfully!",
        js_assist_err: "Error sending. Please try again later.",
        
        js_check_success_title: "Request Sent!",
        js_check_success_text: "Your booking has been successfully registered.<br><br>Code: ",
        js_check_btn_dash: "GO TO DASHBOARD",
        js_check_err_title: "Error",
        js_check_err_text: "An error occurred while sending the request to the database. Please try again shortly.",
        js_check_btn_close: "Close",
        js_check_redirect: "No booking data found.<br><br>Redirecting...",
        
        js_link_exp_title: "Expired or<br>Invalid Link",
        js_link_exp_text: "The security link you used is no longer valid.<br>Please make a new request.",
        js_link_exp_btn: "Request a new link"
    }
};